import { db } from "@workspace/db";
import {
  hotelsTable,
  suppliersTable,
  supplierRoomsTable,
  masterRoomsTable,
  roomMappingsTable,
} from "@workspace/db";
import { count } from "drizzle-orm";
import { logger } from "../lib/logger";
import { TextNormalizer } from "../lib/normalizer";
import { runMappingPipeline } from "../lib/mappingEngine";

const normalizer = new TextNormalizer();

async function seedIfEmpty(): Promise<void> {
  const [supplierCount] = await db.select({ count: count() }).from(suppliersTable);
  if (Number(supplierCount?.count ?? 0) > 0) {
    logger.info("Seed data already exists, skipping");
    return;
  }

  logger.info("Seeding database with hotel room data...");

  await db.insert(hotelsTable).values([
    { id: "hotel-azure-coast", name: "Azure Coast Resort & Spa", location: "Bodrum, Turkey" },
    { id: "hotel-grand-palace", name: "Grand Palace Hotel", location: "Istanbul, Turkey" },
  ]);

  await db.insert(suppliersTable).values([
    { id: "supplier-a", name: "BookingBridge", description: "Global OTA with real-time inventory", syncStatus: "active" },
    { id: "supplier-b", name: "TravelNex Pro", description: "B2B travel wholesale platform", syncStatus: "active" },
    { id: "supplier-c", name: "HotelConnect API", description: "Direct hotel connectivity API", syncStatus: "active" },
  ]);

  const azureCoastRooms = [
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-DLX-KNG-SEA-01",
      rawName: "Deluxe King Room Sea View",
      roomType: "deluxe",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 42,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "air_conditioning", "balcony", "sea_view_terrace"],
      viewType: "sea",
      pricePerNight: 280,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-STD-TWN-GARD-01",
      rawName: "Standard Twin Room Garden View",
      roomType: "standard",
      bedConfig: [{ type: "twin", count: 2 }],
      areaSqm: 32,
      maxOccupancy: 2,
      amenities: ["wifi", "air_conditioning"],
      viewType: "garden",
      pricePerNight: 145,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-STE-PENT-SEA-01",
      rawName: "Penthouse Suite Sea View",
      roomType: "suite",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 120,
      maxOccupancy: 4,
      amenities: ["wifi", "minibar", "jacuzzi", "butler_service", "private_pool", "sea_view"],
      viewType: "sea",
      pricePerNight: 850,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-SUP-KNG-POOL-01",
      rawName: "Superior King Pool View",
      roomType: "superior",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 38,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "air_conditioning", "pool_access"],
      viewType: "pool",
      pricePerNight: 210,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-FAM-TWN-GARD-01",
      rawName: "Family Room Twin Garden",
      roomType: "standard",
      bedConfig: [{ type: "double", count: 1 }, { type: "twin", count: 2 }],
      areaSqm: 55,
      maxOccupancy: 4,
      amenities: ["wifi", "air_conditioning", "garden_view"],
      viewType: "garden",
      pricePerNight: 195,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-VLA-PRIV-01",
      rawName: "Private Pool Villa",
      roomType: "villa",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 180,
      maxOccupancy: 4,
      amenities: ["wifi", "private_pool", "butler_service", "kitchenette", "garden"],
      viewType: "garden",
      pricePerNight: 1200,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-DLX-DBL-CITY-01",
      rawName: "Deluxe Double City View",
      roomType: "deluxe",
      bedConfig: [{ type: "double", count: 1 }],
      areaSqm: 36,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "air_conditioning"],
      viewType: "city",
      pricePerNight: 195,
      currency: "USD",
    },
    // Supplier A unique rooms
    {
      supplierId: "supplier-a",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "AC-STE-HON-01",
      rawName: "Honeymoon Suite with Private Jacuzzi",
      roomType: "suite",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 85,
      maxOccupancy: 2,
      amenities: ["wifi", "jacuzzi", "champagne_welcome", "rose_petals", "sea_view"],
      viewType: "sea",
      pricePerNight: 620,
      currency: "USD",
    },
  ];

  const supplierBRooms = [
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0010",
      rawName: "DLX KNG - Ocean Front",
      roomType: "deluxe",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 42,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "ac", "balcony"],
      viewType: "sea",
      pricePerNight: 265,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0011",
      rawName: "STD TWN Room - Bahce Manzara",
      roomType: "standard",
      bedConfig: [{ type: "twin", count: 2 }],
      areaSqm: 32,
      maxOccupancy: 2,
      amenities: ["wifi", "ac"],
      viewType: "garden",
      pricePerNight: 138,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0012",
      rawName: "Penthouse Ste Ocean Front - Pent Level",
      roomType: "suite",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 120,
      maxOccupancy: 4,
      amenities: ["wifi", "minibar", "jacuzzi", "butler", "pool", "sea"],
      viewType: "sea",
      pricePerNight: 820,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0013",
      rawName: "Sup Kng Pool View Room",
      roomType: "superior",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 38,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "ac", "pool"],
      viewType: "pool",
      pricePerNight: 200,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0014",
      rawName: "Aile Odasi - Bahce - 4 Kisi",
      roomType: "standard",
      bedConfig: [{ type: "double", count: 1 }, { type: "twin", count: 2 }],
      areaSqm: 55,
      maxOccupancy: 4,
      amenities: ["wifi", "ac", "garden"],
      viewType: "garden",
      pricePerNight: 185,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0015",
      rawName: "Private Villa Havuz",
      roomType: "villa",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 180,
      maxOccupancy: 4,
      amenities: ["wifi", "private_pool", "butler", "kitchen", "garden"],
      viewType: "garden",
      pricePerNight: 1150,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "TN-AC-0016",
      rawName: "DLX DBL Sehir Manzara",
      roomType: "deluxe",
      bedConfig: [{ type: "double", count: 1 }],
      areaSqm: 36,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "ac"],
      viewType: "city",
      pricePerNight: 188,
      currency: "USD",
    },
  ];

  const supplierCRooms = [
    {
      supplierId: "supplier-c",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "HC-AZC-D1SEA",
      rawName: "Superior King Seaview",
      roomType: "deluxe",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 42,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "air-con", "balcony", "sea-facing"],
      viewType: "sea",
      pricePerNight: 272,
      currency: "USD",
    },
    {
      supplierId: "supplier-c",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "HC-AZC-S1POOL",
      rawName: "Suite Junior Pool Terrace",
      roomType: "suite",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 68,
      maxOccupancy: 3,
      amenities: ["wifi", "minibar", "pool_view", "terrace", "ac"],
      viewType: "pool",
      pricePerNight: 450,
      currency: "USD",
    },
    {
      supplierId: "supplier-c",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "HC-AZC-STD2",
      rawName: "Standard Room 2 Single Beds Garden",
      roomType: "standard",
      bedConfig: [{ type: "twin", count: 2 }],
      areaSqm: 30,
      maxOccupancy: 2,
      amenities: ["wifi", "ac"],
      viewType: "garden",
      pricePerNight: 130,
      currency: "USD",
    },
    // Edge case: C has this, A and B don't
    {
      supplierId: "supplier-c",
      hotelId: "hotel-azure-coast",
      supplierRoomCode: "HC-AZC-ECO01",
      rawName: "Economy Single Room No View",
      roomType: "standard",
      bedConfig: [{ type: "single", count: 1 }],
      areaSqm: 18,
      maxOccupancy: 1,
      amenities: ["wifi"],
      viewType: "none",
      pricePerNight: 85,
      currency: "USD",
    },
  ];

  const grandPalaceRoomsA = [
    {
      supplierId: "supplier-a",
      hotelId: "hotel-grand-palace",
      supplierRoomCode: "GP-DLX-KNG-BSP-01",
      rawName: "Deluxe King Bosphorus View",
      roomType: "deluxe",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 45,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "air_conditioning", "bosphorus_view"],
      viewType: "sea",
      pricePerNight: 320,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-grand-palace",
      supplierRoomCode: "GP-STE-OTT-01",
      rawName: "Ottoman Suite with City Panorama",
      roomType: "suite",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 110,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "butler", "panoramic_view", "jacuzzi"],
      viewType: "city",
      pricePerNight: 780,
      currency: "USD",
    },
    {
      supplierId: "supplier-a",
      hotelId: "hotel-grand-palace",
      supplierRoomCode: "GP-STD-DBL-CTY-01",
      rawName: "Standard Double City View",
      roomType: "standard",
      bedConfig: [{ type: "double", count: 1 }],
      areaSqm: 28,
      maxOccupancy: 2,
      amenities: ["wifi", "air_conditioning"],
      viewType: "city",
      pricePerNight: 165,
      currency: "USD",
    },
  ];

  const grandPalaceRoomsB = [
    {
      supplierId: "supplier-b",
      hotelId: "hotel-grand-palace",
      supplierRoomCode: "TN-GP-201",
      rawName: "Dlx Kng - Bogazici Manzara",
      roomType: "deluxe",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 45,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "ac", "bosphorus"],
      viewType: "sea",
      pricePerNight: 305,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-grand-palace",
      supplierRoomCode: "TN-GP-202",
      rawName: "Ottoman Ste - Sehir Panorama",
      roomType: "suite",
      bedConfig: [{ type: "king", count: 1 }],
      areaSqm: 110,
      maxOccupancy: 2,
      amenities: ["wifi", "minibar", "butler", "panoramic", "jacuzzi"],
      viewType: "city",
      pricePerNight: 750,
      currency: "USD",
    },
    {
      supplierId: "supplier-b",
      hotelId: "hotel-grand-palace",
      supplierRoomCode: "TN-GP-203",
      rawName: "Standard Dbl Room - City",
      roomType: "standard",
      bedConfig: [{ type: "double", count: 1 }],
      areaSqm: 28,
      maxOccupancy: 2,
      amenities: ["wifi", "ac"],
      viewType: "city",
      pricePerNight: 158,
      currency: "USD",
    },
  ];

  const allRooms = [
    ...azureCoastRooms,
    ...supplierBRooms,
    ...supplierCRooms,
    ...grandPalaceRoomsA,
    ...grandPalaceRoomsB,
  ];

  for (const room of allRooms) {
    const normalized = normalizer.normalize(room.rawName);
    await db.insert(supplierRoomsTable).values({
      supplierId: room.supplierId,
      hotelId: room.hotelId,
      supplierRoomCode: room.supplierRoomCode,
      rawName: room.rawName,
      normalizedName: normalized,
      roomType: room.roomType,
      bedConfig: room.bedConfig,
      areaSqm: room.areaSqm,
      maxOccupancy: room.maxOccupancy,
      amenities: room.amenities,
      viewType: room.viewType,
      pricePerNight: room.pricePerNight,
      currency: room.currency,
      rawData: room,
    });
  }

  logger.info("Running initial mapping pipeline for all suppliers...");

  for (const supplierId of ["supplier-a", "supplier-b", "supplier-c"]) {
    await runMappingPipeline(supplierId);
  }

  logger.info("Seed data and initial mapping complete");
}

export { seedIfEmpty };
